spring.application.name=Course_Management


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/it211_project?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

app.jwt.secret=K6d9F2hXz8WqPlmN4vYtB1rE5cTsG3vA7xZpQ0wKjM9iUhG8fD7sA6dF5gH4jK3l
app.jwt.access-expiration-ms=3600000
app.jwt.refresh-expiration-ms=604800000

cloudinary.cloud-name=dludetzl9
cloudinary.api-key=852316295171968
cloudinary.api-secret=OgzTnVH-KDCor9c9go1Is7bvJr4

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.password-reset.expiration-ms=3600000

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
